photos/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from photos import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^new/$', views.new, name='new'),
    url(r'^(?P<photo_id>\d+)/$', views.detail, name='detail'),
)

travelphotos/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from travelphotos import views

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    url(r'^photos/', include('photos.urls', namespace='photos')),

    url(r'^login/$', 'django.contrib.auth.views.login'),
    url(r'^logout/$', views.logout_page),

    # Examples:
    # url(r'^$', 'travelphotos.views.home', name='home'),
    # url(r'^travelphotos/', include('travelphotos.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)
if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}))

photos/models.py
from django.db import models
from django.contrib.auth.models import User

# For image data parsing
from PIL import Image
from PIL.ExifTags import TAGS, GPSTAGS

class Photo(models.Model):
    title = models.CharField(max_length=50)
    image = models.ImageField(upload_to='images')
    description = models.CharField(max_length=200)
    latitude = models.FloatField(null=True, blank=True)
    longitude = models.FloatField(null=True, blank=True)
    user = models.ForeignKey(User)

    def process_exif(self):
        info = Image.open(self.image.file)._getexif()

        ret = {}
        for tag, value in info.items():
            decoded = TAGS.get(tag, tag)
            ret[decoded] = value

        n_sec = ret['GPSInfo'][2][2][0] / float(ret['GPSInfo'][2][2][1])
        n_min = ret['GPSInfo'][2][1][0] / float(ret['GPSInfo'][2][1][1])
        n_deg = ret['GPSInfo'][2][0][0] / float(ret['GPSInfo'][2][0][1])
        w_sec = ret['GPSInfo'][4][2][0] / float(ret['GPSInfo'][4][2][1])
        w_min = ret['GPSInfo'][4][1][0] / float(ret['GPSInfo'][4][1][1])
        w_deg = ret['GPSInfo'][4][0][0] / float(ret['GPSInfo'][4][0][1])

        if ret['GPSInfo'][1] == 'N':
            n_mult = 1
        else:
            n_mult = -1

        # maybe this should be [1]..
        if ret['GPSInfo'][3] == 'E':
            w_mult = 1
        else:
            w_mult = -1

        latitude = n_mult * (n_deg + (n_min + n_sec/60.0)/60.0)
        longitude = w_mult * (w_deg + (w_min + w_sec/60.0)/60.0)

        return { 'latitude': latitude, 'longitude': longitude }

    def save(self, *args, **kwargs):
        image_data = self.process_exif()
        self.latitude = image_data['latitude']
        self.longitude = image_data['longitude']
        super(Photo, self).save(*args, **kwargs)

photos/forms.py
from django import forms

class PhotoForm(forms.Form):
    title = forms.CharField(max_length=50)
    image = forms.ImageField(
        label='Select a file'
    )

photos/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.template import Context, loader, RequestContext
from django.shortcuts import render_to_response
from django.contrib.auth.decorators import login_required

from photos.models import Photo
from photos.forms import PhotoForm

def index(request):
    photos = Photo.objects.all()

    return render_to_response(
        'photos/index.html',
        {'photos': photos},
        context_instance=RequestContext(request)
    )

def detail(request, photo_id):
    photo = get_object_or_404(Photo, pk=photo_id)
    return render_to_response('photos/detail.html',
                              {'photo': photo},
                              context_instance=RequestContext(request))

@login_required
def new(request):
    if request.method == 'POST':
        form = PhotoForm(request.POST, request.FILES)
        if form.is_valid():
            photo = Photo(
                title = form.cleaned_data['title'],
                image = request.FILES['image'],
                user = request.user,
            )
            photo.save()

            return HttpResponseRedirect(reverse('photos:index'))
    else:
        form = PhotoForm()

    return render_to_response(
        'photos/new.html',
        {'form': form},
        context_instance=RequestContext(request)
    )

travelphotos/views.py
from django.contrib.auth import logout
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response

#def main_page(request):
    #return render_to_response('index.html')

def logout_page(request):
    logout(request)
    return HttpResponseRedirect('/')

photos/templates/photos/detail.html
{% extends 'base.html' %}

{% block body %}
    <p>Title: {{ photo.title }}</p>
    <p>Submitted by: {{ photo.user }}</p>
    <p class="gps">{{ photo.latitude }}, {{ photo.longitude }}</p>
    <br />
    <img src="/{{ photo.image.url }}">
{% endblock %}

photos/templates/photos/index.html
{% extends 'base.html' %}

{% load leaflet_tags %}

{% block includes %}
  <script src="/media/js/map.js" type="text/javascript"></script>
{% endblock %}

{% block body %}
  {% if photos %}
    {% leaflet_map 'photos' callback="window.customMap" %}
    <ul>
      {% for photo in photos %}
      <li>
        <p>Title: {{ photo.title }}</p>
        <p>Submitted by: {{ photo.user }}</p>
        <p class="gps">{{ photo.latitude }}, {{ photo.longitude }}</p>
        <br />
        <a href="/{{ photo.image.url }}">
          <img src="/{{ photo.image.url }}">
        </a></li>
      {% endfor %}
    </ul>
  {% else %}
    <p>None</p>
  {% endif %}
{% endblock %}

photos/templates/photos/new.html
{% extends 'base.html' %}

{% block body %}
  <h2>Add a new picture from your trip</h2>
  <form action="{% url 'photos:new' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <input type="textbox" name="title" id="title" />
    <label for="title">Title</label><br />

    <p>{{ form.non_field_errors }}</p>
    <p>{{ form.image.label_tag }}</p>
    <p>
      {{ form.image.errors }}
      {{ form.image }}
    </p>
    <p><input type="submit" value="Upload" /></p>
  </form>
{% endblock %}

travelphotos/templates/base.html
{% load leaflet_tags %}
{% load staticfiles %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    {% leaflet_js %}
    {% leaflet_css %}
    <script type="text/javascript" src="/media/js/jquery-1.9.1.min.js"></script>
    {% block includes %}{% endblock %}
    <title>
      {% block title %}
      Travel Photos
      {% endblock %}
    </title>
  </head>
  <body>
    {% block body %}{% endblock %}
  </body>
</html>